MIN_LENGTH = 4
MAX_LENGTH = 64
DEFAULT_LENGTH = 16

MIN_NUMBERS = 0
MIN_CHARACTERS = 0
MIN_SYMBOLS = 0

WINDOW_WIDTH = 460
WINDOW_HEIGHT = 560

PUNCTUATION = "!@#$%^&*"
CONFUSING_COMBO = ["i", "I", "l", "L", "1"]